export enum RoutesName {
  index = 'index',
  user = 'user',
  userId = 'user-id',
  auth = 'auth',
  authRegistration = 'auth-registration',
  dashboard = 'dashboard',
  votesMy = 'votes-my',
  polls = 'polls',
  pollsMy = 'polls-my',
  pollId = 'poll-id',
  pollNew = 'poll-new',
  pollNewShareId = 'poll-new-share-id',
  pollNewInviteId = 'poll-new-invite-id',
  pollNewJoinLinkId = 'poll-new-join-link-id',
  pollNewSummaryId = 'poll-new-summary-id',
  pollSettingsId = 'poll-settings-id',
  pollInviteId = 'poll-invite-id',
  pollMembersId = 'poll-members-id',
  accountProfile = 'account-profile',
  accountProfilePassword = 'account-profile-password'
};
